<div align="center">
  <h1><b> Linear Algebra </b></h1>
  <h2> Partial Trace </h2>
</div>

<br>
<b>Author:</b> <a target="_blank" href="https://github.com/camponogaraviera">Lucas Camponogara Viera</a>

# Table of Contents

- [Definition](#definition)
- [Applications](#applications)
- [Examples](#examples)
  - [Reduced Density Matrix of a Bipartite System](#reduced-density-matrix-of-a-bipartite-system)
  - [Measurement in a Bipartite System](#measurement-in-a-bipartite-system)
- [Python Implementation](#python-implementation)

# Definition

The partial trace function is one of the many functions used to extract information about a composite quantum system. For instance, in the context of local operations it is expedient to associate to each subsystem a reduced density operator (a.k.a reduced density matrix) via the partial trace function. 

Let $\mathcal{O}$ denote a linear operator acting on a composite Hilbert space $\mathcal{H}_{ab}  :=  \mathcal{H}_a\otimes\mathcal{H}_b$ of a bipartite system, and $\{b_j\}_{j=1}^{d_b}$ denote any $d_b$-dimensional orthonormal basis set for $\mathcal{H}_b$ with $\dim \mathcal{H}_b = d_b$. The partial trace over subsystem $b$ is a map $Tr_b: \mathcal{L} (\mathcal{H}_{ab}) \rightarrow  \mathcal{L}( \mathcal{H}_a)$ defined as:

\begin{align}
Tr_b(\mathcal{O}) := \sum_{j=1}^{d_b}(\mathbb{I}_a \otimes \langle b_j|) \mathcal{O} (\mathbb{I}_a \otimes | b_j \rangle).
\end{align}

Conversely, the partial trace over subsytem $a$ is a map $Tr_a: \mathcal{L} (\mathcal{H}_{ab}) \rightarrow  \mathcal{L}( \mathcal{H}_b)$ defined as:

\begin{align}
Tr_a(\mathcal{O}) := \sum_{j=1}^{d_a}( \langle a_j|  \otimes \mathbb{I}_b) \mathcal{O} (|a_j \rangle \otimes \mathbb{I}_b).
\end{align}

Furthermore, the partial trace is a function with the property:

\begin{align}
Tr_a(\hat{A} f(\hat{O})) = Tr_{ab}((\hat{A}\otimes \mathbb{I}_b) \hat{O}),
\end{align}

for generic linear operators $\hat{A} \in \mathcal{L}( \mathcal{H}_a)$ and $\hat{O}\in \mathcal{L}(\mathcal{H}_{ab})$.

# Applications

1. The partial trace is used to obtain the `reduced density matrix` (a.k.a partial state or quantum marginal) of a subsystem from the density matrix of a composite (e.g., bipartite) system.
   
2. The partial trace can be used for measurement in a bipartite system.

# Examples

## Reduced Density Matrix of a Bipartite System

One ubiquitous application of the partial trace is to compute the `reduced density matrix` (a.k.a partial state or quantum marginal) of a subsystem.

Here, we derive the analytical expression of the reduced density operator for a bipartite system. The computation of the partial trace for general multipartite systems requires a numerical approach, and is beyond the scope of this introduction.

Let $\rho_{ab} := \rho_a \otimes \rho_b \in \mathcal{H}_{ab}$ denote a density operator of a bipartite system. The partial trace of $\rho_{ab}$ over subsystem $b$ yields a `reduced density operator` $\rho_a \in \mathcal{L}( \mathcal{H}_a)$ of subsystem $a$. This assertion can be verified as follows:

\begin{align}
Tr_b(\rho_{ab})&=\sum_{j=1}^{d_b} (\mathbb{I}_a \otimes \langle b_j|)(\rho_a \otimes \rho_b)(\mathbb{I}_a \otimes | b_j\rangle) \\
&=\sum_{j=1}^{d_b} (\mathbb{I}_a \rho_a \otimes \langle b_j|\rho_b) (\mathbb{I}_a \otimes | b_j\rangle)\\
&=\sum_{j=1}^{d_b} \mathbb{I}_a \rho_a \mathbb{I}_a \otimes \langle b_j| \rho_b| b_j \rangle \\
&= \sum_{j=1}^{d_b} \rho_a \otimes \langle b_j| \rho_b| b_j \rangle,
\end{align}   

Making use of the completeness relation and the unit trace condition $Tr(\rho_b)=1$, one gets:

\begin{align}
Tr_b(\rho_{ab})&= \sum_{j=1}^{d_b} \rho_a \otimes Tr( \langle b_j| \rho_b| b_j \rangle) \\
&= \sum_{j=1}^{d_b} \rho_a \otimes Tr(| b_j \rangle  \langle b_j| \rho_b)\\
&=  \rho_a \otimes Tr\left(\left(\sum_{j=1}^{d_b}| b_j \rangle  \langle b_j|\right) \rho_b\right)\\
&= \rho_a \otimes Tr(\rho_b) = \rho_a \otimes 1 =  \rho_a.
\end{align}

## Measurement in a Bipartite System

A measurement operator in a composite Hilbert space $\mathcal{H}_{ab} := \mathcal{H}_a\otimes\mathcal{H}_b$ of a bipartite system is a local projection operator defined as $M_{ab}:= M\otimes\mathbb{I}_d$. For instance, let $M := M_a := |a_j\rangle\langle a_j| \in \mathcal{L}(\mathcal{H}_a)$ denote a projector operator on subsystem $a$, such that $M_{ab}=M_a \otimes \mathbb{I}_d \in \mathcal{L}(\mathcal{H}_{ab})$. 

Recall that any projector operator satisfies $M_{ab}^{\dagger}M_{ab}=M_{ab}^2=M_{ab}$. The corresponding probabilities associated to the eigenvalue $a_j$ of an observable $\hat{O}_a \in \mathcal{L}(\mathcal{H}_a)$ on subsystem $a$ are given as follows:

\begin{align}
    Pr(a_j|\rho_{ab})
    &=Tr_{ab}((M_{ab}^{\dagger}M_{ab})\rho_{ab})\\
    &=Tr_{ab}( M_{ab}\rho_{ab})\\
    &=Tr_{ab}\left((M_a\otimes \mathbb{I}_d) p_{ab}\right).
\end{align} 

From the partial function definition, one has $Tr_{ab}((M_a \otimes \mathbb{I}_b)\rho_{ab}) = Tr_a(M_a(Tr_b(\rho_{ab}))$, such that

\begin{align}
    Pr(a_j|\rho_{ab}) &= Tr_a(M_a\rho_{a})\\
    &= Tr_a(\rho_{a}M_a)\\
    &= Tr_a(\rho_{a}(|a_j\rangle \langle a_j|)) \\
    &=Tr(\rho_{a}(|a_j\rangle \langle a_j|)),
\end{align} 

where we have dropped the sub-index of the trace function since the argument only depends on terms of subsystem $a$, such that the partial trace becomes the ordinary trace defined in the Trace section. 

# Python Implementation 

Recall that a general 1-qubit state can be written as:

$$ \rho = \frac{1}{2} (\mathbb{I} + \langle x \rangle X + \langle y \rangle Y + \langle z \rangle Z) .$$

In [128]:
import numpy as np 

# Pauli Matrices:

sigma0 = np.identity(2) 
sigma1 = np.array([[0,1],[1,0]], dtype=(np.float32)) 
sigma2 = np.array([[0,-1j],[1j,0]], dtype=(np.complex64)) 
sigma3 = np.array([[1,0],[0,-1]], dtype=(np.float32)) 


Let us implement the following pure density operator for subsystem $a$:

$$ \rho_a = |+\rangle \langle + | .$$

The corresponding coordinates of the Bloch sphere are: $\vec{r} = (1, 0, 0)$.

\begin{align}
\rho_a &= \frac{1}{2} (\mathbb{I} + x_a X + y_a Y + z_a Z) \\
&= \frac{1}{2} (\mathbb{I} + 1 \cdot X + 0 \cdot Y + 0  \cdot Z).
\end{align}

In [129]:
x_a = 1
y_a = 0
z_a = 0

rho_a = (1/2)*(sigma0 + x_a*sigma1 + y_a*sigma2 + z_a*sigma3)
rho_a

array([[0.5+0.j, 0.5+0.j],
       [0.5+0.j, 0.5+0.j]])

In [130]:
# Does rho_a satisfy the properties of a density operator?

eigs = np.linalg.eigvals(rho_a)
print("Trace =", np.trace(rho_a))
print("Hermitian:", np.allclose(rho_a, rho_a.conj().T))
print("Eigenvalues:", eigs)
print("Positive semidefinite:", np.all(eigs >= -1e-12))



Trace = (1+0j)
Hermitian: True
Eigenvalues: [1.0000000e+00+0.j 7.2203753e-33+0.j]
Positive semidefinite: True


Let us implement the density operator for subsystem $b$:

$$ \rho_b = \frac{1}{2} (\mathbb{I} + x_b X + y_b Y + z_b Z).$$

Let us choose the following coordinates for the Bloch sphere: $\vec{r} = (0.5, 0.5, 0)$.

In [131]:
x_b = 0.5
y_b = 0.5
z_b = 0

rho_b = (1/2)*(sigma0 + x_b*sigma1 + y_b*sigma2 + z_b*sigma3)
rho_b

array([[0.5 +0.j  , 0.25-0.25j],
       [0.25+0.25j, 0.5 +0.j  ]])

In [132]:
# Does rho_b satisfy the properties of a density operator?

eigs = np.linalg.eigvals(rho_b)
print("Trace =", np.trace(rho_b))
print("Hermitian:", np.allclose(rho_b, rho_b.conj().T))
print("Eigenvalues:", eigs)
print("Positive semidefinite:", np.all(eigs >= -1e-12))


Trace = (1+0j)
Hermitian: True
Eigenvalues: [0.85355339+2.77555756e-17j 0.14644661-2.77555756e-17j]
Positive semidefinite: True


Let us implement the density operator of the composite system:

\begin{align} 
\rho_{ab} &= \rho_a \otimes \rho_b \\ 
&= \frac{1}{2} (\mathbb{I} + X) \otimes \frac{1}{2} (\mathbb{I} + 0.5 X +  0.5 Y).
\end{align}



In [133]:
# Density operator of the composite bipartite system:

rho_ab = np.kron(rho_a, rho_b)
rho_ab

array([[0.25 +0.j   , 0.125-0.125j, 0.25 +0.j   , 0.125-0.125j],
       [0.125+0.125j, 0.25 +0.j   , 0.125+0.125j, 0.25 +0.j   ],
       [0.25 +0.j   , 0.125-0.125j, 0.25 +0.j   , 0.125-0.125j],
       [0.125+0.125j, 0.25 +0.j   , 0.125+0.125j, 0.25 +0.j   ]])

In [134]:
# Does rho_ab satisfy the properties of a density operator?

eigs = np.linalg.eigvals(rho_ab)
print("Trace =", np.trace(rho_ab))
print("Hermitian:", np.allclose(rho_ab, rho_ab.conj().T))
print("Eigenvalues:", eigs)
print("Positive semidefinite:", np.all(eigs >= -1e-12))


Trace = (1+0j)
Hermitian: True
Eigenvalues: [ 8.53553391e-01-9.41769612e-19j  1.46446609e-01-1.52404719e-17j
  1.78108881e-17-1.28004569e-17j -2.66886422e-18-1.11811773e-18j]
Positive semidefinite: True


Let us compute the partial trace over subsystem $b$ to get the subsystem $a$:

In [135]:
# Space Dimensions of the Subsystems:

da = 2
db = 2

In [136]:
def partial_trace_over_b(da, db, rho_ab):
    rho_a = np.zeros((da, da), dtype=complex)
    for i in range(0, da):
        for j in range(0, da):
            for k in range(0, db):
                rho_a[i,j] += rho_ab[i*db+k,j*db+k]
    return rho_a

rho_a = partial_trace_over_b(da, db, rho_ab)
rho_a

array([[0.5+0.j, 0.5+0.j],
       [0.5+0.j, 0.5+0.j]])

Let us compute the partial trace over subsystem $a$ to get the subsystem $b$:

In [137]:
def partial_trace_over_a(da, db, rho_ab):
    rho_b = np.zeros((db, db), dtype=complex)
    for i in range(0, db):
        for j in range(0, db):
            for k in range(0, da):
                rho_b[i,j] += rho_ab[k*db+i,k*db+j]
    return rho_b

rho_b = partial_trace_over_a(da, db, rho_ab)
rho_b

array([[0.5 +0.j  , 0.25-0.25j],
       [0.25+0.25j, 0.5 +0.j  ]])

# &nbsp; <a href="#"><img valign="middle" height="45px" src="https://img.icons8.com/book" width="45" hspace="0px" vspace="0px"></a> References<a name="ref" />

[1] Nielsen MA, Chuang IL. 2010. Quantum Computation and Quantum Information. New York: [Cambridge Univ. Press.](https://doi.org/10.1017/CBO9780511976667) 10th Anniv. Ed. 